# https://www.electron.build/configuration/configuration#configuration
productName: "Mantarray Controller"
appId: "CuriBio.Mantarray.Controller"
asar: true
directories:
  buildResources: "electron-build-resources"
  output: "dist"
extraFiles:
  - "dist-python/"
files:
  - "package.json"
  - from: "dist/main/"
    to: "dist/main/"
  - from: "dist/renderer/"
    to: "dist/renderer/"
  - from: "src/extraResources/"
    to: ""
win:
  target: "nsis"
  artifactName: "MantarrayController-Setup-prod-${version}.${ext}"
publish:
  provider: "s3"
  bucket: "downloads.curibio.com"
  path: "software"
  channel: "prod"
  region: "us-east-1"
