minimum_pre_commit_version: 2.11.1
fail_fast: false
default_language_version:
  python: python3.10
repos:
  # Git-related
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: forbid-new-submodules
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5 # Use the ref you want to point at
    hooks:
      - id: git-dirty

  # Reformatting (should generally come before any file format or other checks, because reformatting can change things)
  - repo: https://github.com/sqlalchemyorg/zimports
    rev: v0.6.0 # pick a hash or tag to point to
    hooks:
      - id: zimports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      # black and docformatter don't do this in docstrings (11/1/19)
      - id: trailing-whitespace
      - id: fix-encoding-pragma

  - repo: https://github.com/psf/black
    rev: 22.3.0 # pick a git hash / tag to point to
    hooks:
      - id: black
        args: [--line-length=110]
      - id: black
        name: blacken pyinstaller spec
        files: "pyinstaller.spec"
        types: [file]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--print-width=110]
        exclude: sample_waveform_data/|dist/|jsdoc.json

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: tests*

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: detect-private-key

  # Invalid File Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
        name: forbid large files in most places
        args: ["--maxkb=123"]
        exclude: "(src/xem_scripts/)|(electron-build-resources)|(package-lock.json)"
      - id: check-added-large-files
        name: forbid very large files inside src/xem_scripts
        args: ["--maxkb=450"]
        files: "src/xem_scripts"
      - id: check-added-large-files
        name: forbid very large files inside electron-build-resources
        args: ["--maxkb=130"]
        files: "electron-build-resources"
      - id: check-json
      - id: check-yaml
      - id: check-xml
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: end-of-file-fixer

  # Linting
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1 # pick a git hash / tag to point to
    hooks:
      - id: mypy
        name: mypy-controller
        args: [--config-file=controller/mypy.ini, --install-types, --non-interactive]
        files: controller/.*
        exclude: (tests/)|(build.py)

  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter
        exclude: docs

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0 # pick a git hash / tag to point to
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0 # pick a git hash / tag to point to
    hooks:
      - id: flake8
        args: [--config=controller/.flake8]

  - repo: https://github.com/NanoSurface-Biomedical/pre-commit-pylint
    rev: "d805cc60bb5290c2f1ca869d5f1d5e2be720f3fa" # pick a git hash / tag to point to
    hooks:
      - id: python-check-no-print-statments
        exclude: tools/
      - id: vuejs-check-no-console-log-statments
        exclude: ui/pages/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.35.0
    hooks:
      - id: eslint
        name: eslint-electron
        exclude: ^(?!electron/)|(electron_store.js)|(BrowserWinHandler.js)|(dist/)|(tests/)|(\.electron-nuxt)
        files: \.(vue)|(js)$
        types: [file]
        args: [--fix, --config=electron/.eslintrc.js]
      - id: eslint
        name: eslint-ui
        exclude: ^(?!ui/)|(dist/)|(tests/)
        files: \.(vue)|(js)$
        types: [file]
        args: [--fix, --config=ui/.eslintrc.js]
