AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"

# to create: aws cloudformation deploy --stack-name=github-ci-iam-user--mantarray-desktop-app --template-file=ci-iam-formation.yaml --capabilities CAPABILITY_IAM

Description: Create an IAM user with extremely limited permissions that can be used to test access to the parameter store

Parameters:
  Stage:
    Type: String
    Description: The stage for deployment
    AllowedValues:
    - test
    - modl
    - prod
    ConstraintDescription: Must be a valid stage name (test, modl, or prod).
    Default: test

  BuildResourcesBucketName:
    Description: An S3 bucket that contains generally helpful large files---not in the git repo itself. Must be in same region as this stack.
    Type: String
    Default: build-resources-x92toe

Resources:
  TheUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:ListObjects
                  - s3:ListBucket
                Effect: Allow
                Resource:
                  - Fn::Join:
                      - ":"
                      - - "arn"
                        - "aws"
                        - "s3"
                        - ""
                        - ""
                        - Ref: "BuildResourcesBucketName"
                  - Fn::Join:
                      - ":"
                      - - "arn"
                        - "aws"
                        - "s3"
                        - ""
                        - ""
                        - Fn::Join:
                            - "/"
                            - - Ref: "BuildResourcesBucketName"
                              - "*"
          PolicyName: "github-ci-access-mantarray-desktop-app"
  TheUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: TheUser

Outputs:
  AccessKey:
    Value:
      Ref: TheUserAccessKey
    Description: The key for access
  SecretKey:
    Value:
      Fn::GetAtt: TheUserAccessKey.SecretAccessKey
    Description: The secret key for access

