AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"

# Adapted from: https://github.com/aws-samples/aws-codebuild-samples/blob/master/cloudformation/continuous-integration-pull-request-checks.yml
# to create: aws cloudformation deploy --stack-name=codebuild-github-mantarray-desktop-app --parameter-overrides CodeCommitRepoName=mantarray_desktop_app ArtifactsBucketName=build-artifacts-x92toe --template-file=codebuild-formation.yaml --capabilities CAPABILITY_NAMED_IAM

Description: Perform continuous integration pull request checks on a CodeCommit repository with CodeBuild

Parameters:
  CodeCommitRepoName:
    Description: A CodeCommit repository that contains the application code. Must be in same region as this stack.
    Type: String
    # Default: aws-codebuild-samples

  ArtifactsBucketName:
    Description: An S3 bucket to place build artifacts. Must be in same region as this stack.
    Type: String
    # Default: aws-codebuild-samples

  BuildResourcesBucketName:
    Description: An S3 bucket that contains generally helpful large files---not in the git repo itself. Must be in same region as this stack.
    Type: String
    Default: build-resources-x92toe

Resources:
  CodeBuildPolicy:
    Description: Setting IAM policy for service role for CodeBuild
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
          - Action:
              - ssm:GetParameters
            Effect: Allow
            Resource:
              - Fn::Join:
                  - "/"
                  - - "arn:aws:ssm:*:*:parameter/CodeBuild"
                    - Ref: "CodeCommitRepoName"
                    - "testing*"
              - Fn::Join:
                  - "/"
                  - - "arn:aws:ssm:*:*:parameter/CodeBuild"
                    - Ref: "CodeCommitRepoName"
                    - "staging*"
              - Fn::Join:
                  - "/"
                  - - "arn:aws:ssm:*:*:parameter/CodeBuild"
                    - "general"
                    - "*"
          - Action:
              - kms:Decrypt
            Effect: Allow
            Resource: "arn:aws:kms:*:*:alias/aws/ssm"
          - Action:
              - codecommit:GitPull
            Effect: Allow
            Resource: "*"
          - Action:
              - s3:PutObject
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ":"
                  - - "arn"
                    - "aws"
                    - "s3"
                    - ""
                    - ""
                    - Ref: "ArtifactsBucketName"
              - Fn::Join:
                  - ":"
                  - - "arn"
                    - "aws"
                    - "s3"
                    - ""
                    - ""
                    - Fn::Join:
                        - "/"
                        - - Ref: "ArtifactsBucketName"
                          - "*"
              - Fn::Join:
                  - ":"
                  - - "arn"
                    - "aws"
                    - "s3"
                    - ""
                    - ""
                    - Fn::Join:
                        - "/"
                        - - Ref: "BuildResourcesBucketName"
                          - "generic"
                          - "windows"
                          - "codebuild_cache"
                          - "*"
          - Action:
              - s3:GetObject
              - s3:GetBucketAcl
              - s3:GetBucketLocation
              - s3:ListObjects
              - s3:ListBucket
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ":"
                  - - "arn"
                    - "aws"
                    - "s3"
                    - ""
                    - ""
                    - Ref: "BuildResourcesBucketName"
              - Fn::Join:
                  - ":"
                  - - "arn"
                    - "aws"
                    - "s3"
                    - ""
                    - ""
                    - Fn::Join:
                        - "/"
                        - - Ref: "BuildResourcesBucketName"
                          - "*"
      PolicyName:
        Fn::Join:
          - "-"
          - - Ref: "AWS::StackName"
            - CodeBuildPolicy
      Roles:
        - Ref: "CodeBuildRole"
    Type: AWS::IAM::Policy

  CodeBuildProject:
    DependsOn:
      - CodeBuildPolicy
    Properties:
      Artifacts:
        Location:
          Ref: "ArtifactsBucketName"
        Packaging: ZIP
        OverrideArtifactName: true # This is equivalent to checking the "Enable Semantic Versioning" box in the console
        Type: S3
      SecondaryArtifacts:
        - ArtifactIdentifier: "TestArtifacts"
          Location:
            Ref: "ArtifactsBucketName"
          Packaging: ZIP
          OverrideArtifactName: true # This is equivalent to checking the "Enable Semantic Versioning" box in the console
          Type: S3
        - ArtifactIdentifier: "InstallerArtifacts"
          Location:
            Ref: "ArtifactsBucketName"
          Packaging: NONE
          OverrideArtifactName: true # This is equivalent to checking the "Enable Semantic Versioning" box in the console
          Type: S3
      BadgeEnabled: true
      Description:
        Fn::Join:
          - ""
          - - "CodeBuild Project for "
            - Ref: "AWS::StackName"
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/windows-base:2019-1.0-20.11.19
        Type: WINDOWS_SERVER_2019_CONTAINER
        EnvironmentVariables:
          - Name: SAVE_ARTIFACTS
            Type: PLAINTEXT
            Value: "0"
          - Name: PYTEST_RANDOMLY_SEED
            Type: PLAINTEXT
            Value: ""

      Name: "Github-Mantarray-Desktop-App"

      ServiceRole:
        Ref: "CodeBuildRole"
      Source:
        Auth:
          Type: "OAUTH"
        GitCloneDepth: 1

        ReportBuildStatus: True
        Location: "https://github.com/CuriBio/mantarray-desktop-app/"
        Type: GITHUB
      QueuedTimeoutInMinutes: 10
      TimeoutInMinutes: 45
      Cache:
        Location:
          Fn::Join:
            - "/"
            - - Ref: "BuildResourcesBucketName"
              - "generic"
              - "windows"
              - "codebuild_cache"
        Type: "S3"
    Type: AWS::CodeBuild::Project

  CodeBuildRole:
    Description: Creating service role in IAM for AWS CodeBuild
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Path: /
      RoleName:
        Fn::Join:
          - "-"
          - - Ref: "AWS::StackName"
            - CodeBuild
    Type: AWS::IAM::Role
